# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs

# Conventional Commits
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]

# Swift formatting and linting (if tools are available)
-   repo: local
    hooks:
    -   id: swiftformat
        name: SwiftFormat
        entry: bash -c 'if command -v swiftformat >/dev/null 2>&1; then swiftformat . --config .swiftformat; else echo "❌ SwiftFormat not found, please install it (e.g. brew install swiftformat)" >&2; exit 1; fi'
        language: system
        files: \.swift$
        pass_filenames: false
        require_serial: true
    -   id: swiftlint
        name: SwiftLint
        entry: bash -c 'if command -v swiftlint >/dev/null 2>&1; then swiftlint --fix --config .swiftlint.yml; else echo "❌ SwiftLint not found, please install it (e.g. brew install swiftlint)" >&2; exit 1; fi'
        language: system
        files: \.swift$
        pass_filenames: false
        require_serial: true
